-- ==============================================================================
-- X-RAY PROTOCOL - BANCO DE DADOS (SUPABASE)
-- Schema consolidado e idempotente
-- Nota: internal_id e id sao identificadores tecnicos, NAO sao rank visual.
-- Para "ordem tipo Excel", use as views com ROW_NUMBER().
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- TABELA: PROFILES (Identidade Principal)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fid BIGINT PRIMARY KEY,
    username TEXT,
    wallet_address TEXT,
    genesis_nft BOOLEAN DEFAULT FALSE,
    xp BIGINT DEFAULT 0,
    tier INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Colunas extras (seguro para tabelas ja existentes)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS wallet_address TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS genesis_nft BOOLEAN DEFAULT FALSE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS xp BIGINT DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS tier INTEGER DEFAULT 1;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS pfp_url TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS points BIGINT DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS nft_score BIGINT DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS total_points BIGINT DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS neynar_score NUMERIC DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS secondary_nfts INTEGER DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS streak_count INTEGER DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS best_streak INTEGER DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS last_checkin TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS notification_token TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS notification_url TEXT;

-- Garante internal_id mesmo em bases antigas
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS internal_id BIGINT;
CREATE SEQUENCE IF NOT EXISTS public.profiles_internal_id_seq;
ALTER TABLE public.profiles ALTER COLUMN internal_id SET DEFAULT nextval('public.profiles_internal_id_seq');
UPDATE public.profiles
SET internal_id = nextval('public.profiles_internal_id_seq')
WHERE internal_id IS NULL;
SELECT setval(
  'public.profiles_internal_id_seq',
  COALESCE((SELECT MAX(internal_id) FROM public.profiles), 1),
  true
);

CREATE INDEX IF NOT EXISTS idx_profiles_wallet_address ON public.profiles(wallet_address);
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_internal_id_unique ON public.profiles(internal_id);

-- ------------------------------------------------------------------------------
-- TABELA: CHECKINS (Engajamento Diario)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.checkins (
    fid BIGINT PRIMARY KEY,
    streak INTEGER DEFAULT 0,
    best_streak INTEGER DEFAULT 0,
    last_date DATE,
    history JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.checkins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo para a API" ON public.checkins;
CREATE POLICY "Permitir tudo para a API" ON public.checkins
    FOR ALL USING (true) WITH CHECK (true);

-- ------------------------------------------------------------------------------
-- TABELA: LEADERBOARD (Ranking e Pontuacao Global)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.leaderboard (
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fid BIGINT PRIMARY KEY,
    username TEXT,
    "pfpUrl" TEXT,
    pfp_url TEXT,
    points BIGINT DEFAULT 0,
    "hasNft" BOOLEAN DEFAULT FALSE,
    has_nft BOOLEAN DEFAULT FALSE,
    "nftCount" INTEGER DEFAULT 0,
    nft_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.leaderboard ADD COLUMN IF NOT EXISTS base_points BIGINT DEFAULT 0;
ALTER TABLE public.leaderboard ADD COLUMN IF NOT EXISTS total_points BIGINT DEFAULT 0;
ALTER TABLE public.leaderboard ADD COLUMN IF NOT EXISTS nft_score BIGINT DEFAULT 0;
ALTER TABLE public.leaderboard ADD COLUMN IF NOT EXISTS neynar_score NUMERIC DEFAULT 0;
ALTER TABLE public.leaderboard ADD COLUMN IF NOT EXISTS streak INTEGER DEFAULT 0;
ALTER TABLE public.leaderboard ADD COLUMN IF NOT EXISTS best_streak INTEGER DEFAULT 0;

-- Garante internal_id mesmo em bases antigas
ALTER TABLE public.leaderboard ADD COLUMN IF NOT EXISTS internal_id BIGINT;
CREATE SEQUENCE IF NOT EXISTS public.leaderboard_internal_id_seq;
ALTER TABLE public.leaderboard ALTER COLUMN internal_id SET DEFAULT nextval('public.leaderboard_internal_id_seq');
UPDATE public.leaderboard
SET internal_id = nextval('public.leaderboard_internal_id_seq')
WHERE internal_id IS NULL;
SELECT setval(
  'public.leaderboard_internal_id_seq',
  COALESCE((SELECT MAX(internal_id) FROM public.leaderboard), 1),
  true
);

ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo para a API" ON public.leaderboard;
CREATE POLICY "Permitir tudo para a API" ON public.leaderboard
    FOR ALL
    USING (true)
    WITH CHECK (true);

CREATE UNIQUE INDEX IF NOT EXISTS idx_leaderboard_internal_id_unique ON public.leaderboard(internal_id);
CREATE INDEX IF NOT EXISTS idx_leaderboard_total_points_desc ON public.leaderboard(total_points DESC, fid ASC);

-- ------------------------------------------------------------------------------
-- TABELA: USERS (Dados Basicos do Farcaster)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
    fid BIGINT PRIMARY KEY,
    username TEXT,
    display_name TEXT,
    pfp_url TEXT,
    neynar_score NUMERIC DEFAULT 0,
    follower_count INTEGER DEFAULT 0,
    following_count INTEGER DEFAULT 0,
    verified_wallets TEXT[] DEFAULT ARRAY[]::TEXT[],
    primary_wallet TEXT,
    synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS neynar_score NUMERIC DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS follower_count INTEGER DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS following_count INTEGER DEFAULT 0;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS verified_wallets TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS primary_wallet TEXT;

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo para a API" ON public.users;
CREATE POLICY "Permitir tudo para a API" ON public.users
    FOR ALL USING (true) WITH CHECK (true);

-- ------------------------------------------------------------------------------
-- TABELA: POINT_TRANSACTIONS (Historico de tarefas e ganhos)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fid BIGINT NOT NULL,
    event_type TEXT NOT NULL,
    points_earned INTEGER NOT NULL,
    meta JSONB DEFAULT '{}'::jsonb,
    event_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_point_trans_daily
ON public.point_transactions(fid, event_type, event_date);

ALTER TABLE public.point_transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir tudo para a API" ON public.point_transactions;
CREATE POLICY "Permitir tudo para a API" ON public.point_transactions
FOR ALL USING (true) WITH CHECK (true);

-- ------------------------------------------------------------------------------
-- VIEW: LEADERBOARD_RANKED (ranking dinamico por pontos)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.leaderboard_ranked AS
SELECT
    ROW_NUMBER() OVER (ORDER BY total_points DESC, fid ASC) AS rank,
    l.*
FROM public.leaderboard l
ORDER BY rank ASC;

-- ------------------------------------------------------------------------------
-- VIEW: PROFILES_RANKED (ordem visual tipo Excel por points)
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.profiles_ranked AS
SELECT
    ROW_NUMBER() OVER (ORDER BY points DESC, fid ASC) AS linha,
    p.*
FROM public.profiles p
ORDER BY linha ASC;

